// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEUC_lTEVIBHf9vhcLf_UsN-U4Ppes1ZQ',
    appId: '1:487095794997:web:c5c1389f013e5e9880a07c',
    messagingSenderId: '487095794997',
    projectId: 'ridewithme-26d2b',
    authDomain: 'ridewithme-26d2b.firebaseapp.com',
    storageBucket: 'ridewithme-26d2b.appspot.com',
    measurementId: 'G-VQFMDL3DV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctlKPN7d5KN25f4FfxnXVToKtBH4Ypcs',
    appId: '1:487095794997:android:a17ae52d67e33b9480a07c',
    messagingSenderId: '487095794997',
    projectId: 'ridewithme-26d2b',
    storageBucket: 'ridewithme-26d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYwkFZDoiM4hHr5A-bjdTV1mvbAnMNDg',
    appId: '1:487095794997:ios:d1dacbd5d57491ee80a07c',
    messagingSenderId: '487095794997',
    projectId: 'ridewithme-26d2b',
    storageBucket: 'ridewithme-26d2b.appspot.com',
    iosClientId: '487095794997-j15sagoo0nt8cuqd2o2q4qai57fs3j9j.apps.googleusercontent.com',
    iosBundleId: 'cz.muni.fi.pv239.rideWithMe',
  );
}
