@startuml
entity User {
    userId: uuid
    displayName: string
}

entity CustomUser {
    uid: string <<PK>>
    firstName: string
    lastName: string
    aboutMe: string
}

entity Ride {
    *id: int <<PK>>
    *title: string
}

User ||..|| UserProfile

@enduml